
FROM amd64/node:16-alpine

WORKDIR /app

COPY . .
RUN npm install
ENV VITE_MAINTAINED_LOGIN_URL=${MAINTAINED_LOGIN_URL}
ENV VITE_MAINTAINED_API_BASE=${MAINTAINED_API_BASE}
ENV VITE_MAINTAINED_TAI_BASE=${MAINTAINED_TAI_BASE}
RUN npm run build

EXPOSE 3000
CMD ["node", "./build"]