name: Build Maintained Nightly

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: nightly
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/maintained:nightly
