name: Nightly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.sdbagel.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build & Push
        uses: docker/build-push-action@v2
        env:
          MAINTAINED_LOGIN_URL: ${{ secrets.MAINTAINED_LOGIN_URL }}
          MAINTAINED_API_BASE: ${{ secrets.MAINTAINED_API_BASE }}
          MAINTAINED_TAI_BASE: ${{ secrets.MAINTAINED_TAI_BASE }}
        with:
          context: .
          push: true
          tags: registry.sdbagel.com/maintained:nightly
